version: '3.4'

services:
  services:
    build:
      context: ../
      dockerfile: ./services/docker/Dockerfile
    volumes:
      - ../:/app
    ports:
      - 8080:8080

  filestorage:
    build:
      context: ../
      dockerfile: ./file_storage/docker/Dockerfile
    volumes:
      - ../:/app
    ports:
      - 8081:8081