version: '3.4'

services:
  services:
    build:
      context: ../
      dockerfile: ./services/docker/Dockerfile
    volumes:
      - ../:/app
    ports:
      - 8080:8080
    network_mode: "host"

  filestorage:
    user: "1000"
    depends_on:
      - "services"
    build:
      context: ../
      dockerfile: ./file_storage/docker/Dockerfile
    volumes:
      - ../:/app
      - storage-path:/app/file_storage/files
    ports:
      - 8081:8081
    network_mode: "host"

volumes:
  storage-path:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/janne/files